### ISSUE TITLE
Graphical glitches in netdimm menu vertical mode

### ISSUE THREAD

**Issue by chunksin** [DragonMinded/netboot#11]
Some graphical glitches present in the up/down cursors and fonts in vertical mode of the netdimm menu

**Comment by DragonMinded** [comment]
Are they localized to a particular spot on the screen? Does it happen every time?

**Comment by chunksin** [comment]
Probably easiest to show a picture of what is going on: https://drive.google.com/file/d/1RoL45B8K_IoVoU3bXBBgjSoXD0lIjdvp/view?usp=sharing

The initial screen text looks OK, the cursors are pixelated, then start to scroll and the letters break up. Have tried your original and a different font but the same result with both.

**Comment by DragonMinded** [comment]
It looks like something is messing with the VRAM entries for the sprites responsible for said characters. I don't think I've seen this on an unmodified menu, but its been a bit since I've booted it on my vertical setup. I can try and check sometime today.

**Comment by DragonMinded** [comment]
I've checked in vertical and horizontal mode using the checked in netdimm menu as well as one just compiled off of the latest toolchain. None have graphical glitches. Possibly you have made some modifications that mess with VRAM? Or there's some thing not present in the bug report that is important.

**Comment by chunksin** [comment]
I made 2 adjustments, used a different font and added the menu page up/page down using left/right. Would either mess with VRAM?

**Comment by denoh87** [comment]
![275182389_4887862037917299_8842466464878220428_n](https://user-images.githubusercontent.com/101296740/157551106-9309be3c-ef52-486d-8a83-b52e9ee3dfb2.jpg)

Hi DragonMinded. I was directed here regarding the OSM homebrew for the Naomi Netboot. Not sure if my image attached itself correctly. 
When I load the OSM the image appears doubled on screen. Almost similiar to when a 31k image is sent to a 15k monitor / system. (my Naomi is set to 15k via dipswitches and my monitor is 15k only).

**Comment by DragonMinded** [comment]
Depending on if there's a bug, that would definitely mess with things. I can't repro this on stock so you're gonna need to either figure out what modification does it or send me code I can dig into.

**Comment by chunksin** [comment]
Just built from latest code on a Pi 4, no mods and its still displaying the same issues as in the screenshot I'm afraid

**Comment by chunksin** [comment]
Interesting - I've switched to 15Khz horizontal mode and the top arrow is glitching in the same way after going up and down the list

**Comment by DragonMinded** [comment]
I do believe that if you build from latest libnaomi, this should be fixed.

**Comment by chunksin** [comment]
Thanks, I rebuilt my environment from scratch and its working perfectly now, thanks very much for your support! :)
