### ISSUE TITLE
OSM image doubled on screen

### ISSUE THREAD

**Issue by denoh87** [DragonMinded/netboot#13]
Sorry for the repost, I have realised I put it in the wrong spot earlier.

when loading the OSM, the image is doubled on screen.
![275182389_4887862037917299_8842466464878220428_n](https://user-images.githubusercontent.com/101296740/157568767-7758f04e-2d55-48e5-ba54-e65032fcf558.jpg)

first thoughts are that it is similar to when a 31k signal is sent to a 15k monitor, however Naomi is set to 15k on dipswitches and the monitor chassis is 15k.

**Comment by DragonMinded** [comment]
libnaomi doesn't currently support 15khz/interlaced modes, hence why you see a double image.

**Comment by DragonMinded** [comment]
I've added simple 15khz support to libnaomi toolchain. It looks kinda ugly and I'm sure that with some finessing of registers it might look a bit better. However, it should at least work for your case now. Go ahead and give the latest menu a try.

**Comment by DragonMinded** [comment]
I'm going to try to work on the ugliness tomorrow, by the way, if you want to hold off trying until later.

**Comment by DragonMinded** [comment]
I got a much much better interlaced picture from some changes tonight, but I ran out of time before I could push them. So I'll have to wait until tomorrow to clean it up.

**Comment by DragonMinded** [comment]
This should be fixed! 15khz mode is now fully supported in libnaomi and compiled into the default OSM. chunksin will have to compile against the newest release to get that in his fork, however. Closing since this is fixed in base!
