### ISSUE TITLE
SH-4 GCC pass-2 build fails with "configure: error: Link tests are not allowed after GCC_NO_EXECUTABLES."

### ISSUE THREAD

**Issue by rattboi** [DragonMinded/netboot#3]
I'm trying to build the toolchain to experiment with some homebrew, but the pass2 of the SH-4 GCC build fails with the following:

`configure: error: Link tests are not allowed after GCC_NO_EXECUTABLES.`

More context around the error:
https://gist.github.com/rattboi/9c116eb26197712af1fde5bbbe3973f3

**Comment by PrawnCocktail** [comment]
Same problem here, did you find a solution?
I have tried using Debian 10 x64, x86 and lubuntu 20.04 x64 without luck.
This is the config log for libobjc. 
https://gist.github.com/PrawnCocktail/9000b8bc38a5e571b86f38bbdc97e8c8
Any help would greatly appreciated :-)

**Comment by rattboi** [comment]
I forgot to respond to this, sorry.

You can build it following the instructions if you remove one small bit from the newlib.patch file.
If you remove `-DREENTRANT_SYSCALLS_PROVIDED` from `setup/newlib.patch`, it'll build (and seems to work for me).

Not sure what the real issue is yet.

Alternatively, I have dockerized the toolchain, which you can pull. https://hub.docker.com/r/rattboi/naomi-build

I'm still working on making it fully work, but you can see an example of it in use at https://github.com/rattboi/opennaomi/

**Comment by DragonMinded** [comment]
That seems.....wrong? Reentrant syscalls define is necessary for the _r version of all of the syscalls in https://github.com/DragonMinded/netboot/blob/trunk/homebrew/libnaomi/system.c to be picked up. Without it, IIRC there's another calling convention and you should get linker errors. Not sure what's going on here.

**Comment by rattboi** [comment]
I'm assuming some other piece is missing, but I'm no toolchain expert, so anything I've done is just a hack. I started from the commit with the initial instructions for building the toolchain and have rolled forward one commit at a time, piece by piece. SH4 GCC build pass 2 breaks when the reentrant syscalls bit is added to newlib.

**Comment by DragonMinded** [comment]
I'm no expert either. I relied heavily on how kallistios did things, and slowly built up until I had a working toolchain that linked and produced valid assembly when scrutinized. GCC is super hard to dig into :\

**Comment by DragonMinded** [comment]
I just ran into this trying to remake a clean environment and it appears that libobjc is just kinda broken? The proposed patch changes to newlib did not work (I didn't think they would) and it doesn't seem to respect the passed-in flag "--disable-tls" since it attempts to check for thread-local storage anyway. I succeeded in recompiling by disabling objc and objc++ which weren't used in any of the homebrew examples anyway. If this works after I do a from-scratch recompile I'll push that and see if it doesn't fix the issue for some people.

**Comment by DragonMinded** [comment]
Okay, I successfully built completely from scratch and bootstrapped the whole process and the compiled executables were a match for the old toolchain. So as of 030d9db605293d773fe0ee27468246ac6693c361 I believe that this is fixed. If somebody could confirm that would be excellent!

**Comment by rattboi** [comment]
I'll take a stab at it later today. I'm hoping to help with the netdimm loader menu.

**Comment by DragonMinded** [comment]
Any luck?

**Comment by rattboi** [comment]
Yep, it built and seems mostly functional. I guess I need to make a virtualenv as well and get PIL and your arcadutils in it before most of the examples will fully build, but the main compilation steps all work. Just failing on the post-processing.

Do you already have instructions around that part in your repo? Would be worth adding, if not.

**Comment by DragonMinded** [comment]
Pretty much what's on the default readme in the root of the project. You should be able to create a virtualenv and then just run `python3 -m pip install -r requirements.txt` in the root and you should be good.

**Comment by DragonMinded** [comment]
Anyway, if the toolchain is building, I'll close this task. Thanks!
