### ISSUE TITLE
Can't build libnaomi, missing audio.c

### ISSUE THREAD

**Issue by rattboi** [DragonMinded/netboot#4]
It seems there are files not checked in, as libnaomi won't build and the makefile references an audio.c file that does not exist.

**Comment by rattboi** [comment]
Likewise, the related arm/aica files are missing that are referenced in the makefile. Commenting these out allows the rest of the library to build.

**Comment by DragonMinded** [comment]
The quick fix is the right one for now, I think I messed up a check-in way back when. However, I haven't had the chance to figure out why audio crashes on hardware yet as I've been moving for some time.

**Comment by DragonMinded** [comment]
The top-level make works once again after cleaning up some broken files, although audio still does not work properly. I suspect I need to copy samples to the right wave RAM and that I am not doing that at the moment, but its low on my priority list to figure out.
